# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/wush978/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap

# Adapt as necessary starting from here

build_script:
  - Rscript -e "install.packages(c('stringr','testthat','httr','yaml','RCurl','digest','tools','rappdirs'), repos = 'http://wush978.github.io/R')"
  - Rscript -e "install.packages(c('swirl'), repos = c('http://wush978.github.io/R'))"

test_script:
  - Rscript .test_course.R push

on_failure:
  - travis-tool.sh dump_logs

environment:
  R_VERSION: release
