language: r
sudo: false
latex: false

install:
  - Rscript -e "install.packages('remotes')"
  - Rscript -e "utils::install.packages('git2r')"
  - Rscript -e "remotes::install_github('wush978/swirlify@master')"
  - Rscript -e "source('https://wush978.github.io/R/init-swirl.R')"
  - wget https://raw.githubusercontent.com/wush978/R/gh-pages/.test_course.R

matrix:
  include:
    - r: oldrel
      os: linux
      script:
        - Rscript .test_course.R push
      addons: 
        apt:
          packages:
            - libxml2-dev
            - libcurl4-openssl-dev 
            - libssl-dev
    - r: release
      os: linux
      script:
        - Rscript -e "options(editor = function(file, title){});library(swirlify);set_lesson(file.path(getwd(), '00-Hello-DataScienceAndR', 'lesson.yaml'));source('https://raw.githubusercontent.com/wush978/R/gh-pages/transform.R');transform_all()"
        - Rscript .test_course.R push
      addons: 
        apt:
          packages:
            - libxml2-dev
            - libcurl4-openssl-dev 
            - libssl-dev
    - r: release
      os: linux
      script:
        - Rscript .test_course.R push
      addons: 
        apt:
          packages:
            - libxml2-dev
            - libcurl4-openssl-dev 
            - libssl-dev
    - r: release
      os: osx
      script:
      - Rscript .test_course.R push
    

notifications:
  email:
    on_success: change
    on_failure: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8552957f2dea4217e0ed
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

